README.md

The timeout mode by @aarongorka is my favorite, but I wanted to spice it up a bit.

Russian Roulette timeout

---

README.md

`:@"` will execute the buffer. Write the `:qa!` in an empty buffer and execute it.

Use vim against itself with @

---

README.md

added colon-less way

---

README.md

Yes, we need another vim to exit current vim!

The Vim way to finish the life of vim

---

README.md

A little dangerous and excessive, but it works.

The yolo way of exiting vim

---

README.md

The {Microsoft, Passive, Passive-Aggressive} Way

---

README.md

Use another vim client to shut your instance of vim down

The client-server way

---

README.md

Maybe this is not as silly as it sounds...

The Docker Way

---

README.md

When ran, a php server is started, firefox opens the page, user clicks on button, php finds and kills all running vim instances

made a php server that opens a page that kills vim

---

README.md

Added suspend method to exit Vim. Hit ^Z (Ctrl-Z) to suspend job then kill using ps and grep.

added suspend vim exit method

---

README.md

(compile a kernel module that send sigkill to every task called vim. insmod it. rmmod it. and then clean up)

The Kernel way

---

README.md

Credit: @johnoct
1. Don't even try to exit on your own
2. Ask Senior right away

Add The Intern way

---

README.md

Free service, no charge whatsoever. With a few steps I will be able to ssh into your box and kill vim for you!

 I will kill vim for you via ssh (Update README.md)

---

README.md

Exiting vim in a way that frees your soul

spiritual way to exit vim

---

README.md

Pure shell commands is so out of season. Let's use ruby for any task ~(calling shell commands)~, even exit vim in the right way.

Add Rubist using shell way

---

README.md

Add the astronomer's method

---

README.md

The Passive-Aggressive Abstinence Method

---

README.md

When you've moved from Intern to an entry level SWE

Entry level SWE way

---

README.md

I think the plural is criteria https://www.dictionary.com/browse/criterion?s=t
And here the plural is to be used, or not?

single letter typo fix

---

README.md

Stolen from https://news.ycombinator.com/item?id=21990828

The Scrum manager way

---

README.md

The Vagrant way

---

README.md

The Matrix way

---

README.md

The customer success way

---

README.md

Add MacBook Pro Touch Bar way

---

README.md

This add's a short topological way used by mathematicians to exit vim quickly.

Add the mathematician's way

---

README.md

How to exit vim using perl.. Without letting perl call a shell.

Added pure perl method

---

README.md

Add The AWS Way

---

README.md

Gotta admit, I was surprised this wasn't already here.

added an obligatory Emacs method.

---

README.md

The answer everyone googling this problem were looking for.

The Stack Overflow way

---

README.md

Works on Ubuntu, should work on anything besides Windows.

Added "The Go Way"

---

README.md

Requested: https://twitter.com/caseyjohnellis/status/1277036549855604736

Add first contact way

---

README.md

added method using ssh, python, pgrep, grep, sed, cat and even a temporary file!

The layered Method

---

README.md

A very colorful and veeery slow way to exit vim! It might help you to get over this constant fight against vim..
!

added the epileptic method

---

README.md

fix broken codeblock; format non-formated codeblocks

fix: format code, fix mistake
